name: AR

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
        - main
        - development
# - ${{ vars.STABILIZATION_BRANCH }}

jobs:
    Cache-LFS:
        

    Windows-Profile:
        uses: ./.github/workflows/windows-profile.yml
        secrets: inherit
    Windows-Asset:
        needs: Windows-Profile
        uses: ./.github/workflows/windows-asset.yml
    Windows-Test:
        needs: Windows-Asset
        uses: ./.github/workflows/windows-cpu-test.yml
        
    Linux-Profile:
        uses: ./.github/workflows/linux-profile.yml
        secrets: inherit
    Linux-Asset:
        needs: Linux-Profile
        uses: ./.github/workflows/linux-asset.yml
    Linux-Test:
        needs: Linux-Asset
        uses: ./.github/workflows/linux-cpu-test.yml

    Android-Profile:
        uses: ./.github/workflows/android-profile.yml
        secrets: inherit
    # Android-Asset:
    #     uses: ./.github/workflows/android-asset.yml
    # Android-Gradle:
    #     uses: ./.github/workflows/android-gradle.yml
