# .github/workflows/dco.yml
name: DCO
on:
  push:
jobs:
  DCO-Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Set up dco-check
      run: |
        # pip3 install -U dco-check
        curl https://raw.githubusercontent.com/amzn-changml/dco-check/fixup-feature/dco_check/dco_check.py -o /tmp/dco_check.py
    - name: Check DCO
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python /tmp/dco-check.py -f
