# .github/workflows/dco.yml
name: DCO
on:
  push:
jobs:
  DCO-Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Set up dco-check
      run: |
        pip3 install -U dco-check
    - name: Check DCO
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dco-check      
