name: Linux

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang]
        config: [profile]
        image: [ubuntu-20.04]

    runs-on: ${{ matrix.image }}

    env:
      CC:  ${{ matrix.compiler == 'gcc' && 'gcc' || 'clang'   }}
      CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 10240
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-android: 'true'     
            
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: O3DE-linux-${{ matrix.image }}-${{ matrix.config }}-${{ matrix.compiler }}

      - name: Configure environment
        run: |
          echo "Installing dependancies"
          pushd ./scripts/build/build_node/Platform/Linux
          sudo ./install-ubuntu.sh
          popd
          echo "Getting python..."
          ./python/get_python.sh
         
      - name: Configure
        run: |
          echo "Generating project..."
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -G 'Ninja Multi-Config' -DLY_3RDPARTY_PATH=./3rdParty
          
      - name: Build
        run: |
          cmake --build build --target Editor --config ${{ matrix.config }}

      - uses: actions/upload-artifact@v2
        with:
          name: O3DE-linux-${{ matrix.image }}-${{ matrix.config }}-${{ matrix.compiler }}
          path: build/${{ matrix.config }}
