name: Linux

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang]
        config: [profile]
        image: [ubuntu-20.04]

    runs-on: ${{ matrix.image }}

    env:
      CC:  ${{ matrix.compiler == 'gcc' && 'gcc' || 'clang'   }}
      CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache
      BUILDCACHE_MAX_CACHE_SIZE: 10737418240
      BUILDCACHE_REMOTE: $(( secrets.TEST_BUILDCACHE_REMOTE }}
      BUILDCACHE_S3_ACCESS: $(( secrets.TEST_BUILDCACHE_KEY }}
      BUILDCACHE_S3_SECRET: $(( secrets.TEST_BUILDCACHE_SECRET }}

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8196
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-android: 'true'     
            
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      #- uses: hendrikmuhs/ccache-action@v1.2.3
      #  with:
      #    key: O3DE-linux-${{ matrix.image }}-${{ matrix.config }}-${{ matrix.compiler }}
      #    max-size: 2048M
      
      - name: buildcache-action
        uses: mikehardy/buildcache-action@v2.1.0
        with:
          cache_key: O3DE-linux-${{ matrix.image }}-${{ matrix.config }}-${{ matrix.compiler }}
          upload_buildcache_log: 'true' # optional: 100% cache misses? Find out why
          zero_buildcache_stats: 'false' # optional: lifetime vs per-run stats?
        
      - name: Configure environment
        run: |
          echo "Installing dependancies"
          pushd ./scripts/build/build_node/Platform/Linux
          sudo ./install-ubuntu.sh
          popd
          echo "Getting python..."
          ./python/get_python.sh
         
      - name: Configure
        run: |
          echo "Generating project..."
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DLY_3RDPARTY_PATH=./3rdParty
          
      - name: Build
        run: |
          cmake --build build --target Editor --config ${{ matrix.config }}

      - uses: actions/upload-artifact@v3
        with:
          name: O3DE-linux-${{ matrix.image }}-${{ matrix.config }}-${{ matrix.compiler }}
          path: build/**/bin/${{ matrix.config }}
