name: Linux Asset Profile

on:
  push:
    paths: '.github/workflows/linux-asset.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  Build-Asset:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang]
        config: [profile]
        image: [ubuntu-22.04]
        platform: [Linux]
        type: [asset_profile]

    runs-on: ${{ matrix.image }}

    steps:          
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 8000
          temp-reserve-mb: 2000
          swap-size-mb: 200
          remove-dotnet: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
            
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
        with:
          show-progress: false
          
      - name: Git LFS fetch
        run: |
          git lfs install
          git lfs fetch --all
          git lfs checkout

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2
          
      - name: Restore 3P Cache
        uses: actions/cache/restore@v4.0.2
        continue-on-error: true
        with:
          path: |
            ${{ github.workspace }}/3rdParty/packages
            ${{ github.workspace }}/python
          key: O3DE-${{ matrix.platform }}-3p

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1.4.3
        continue-on-error: true
        if: always()
        with:
          override_cache_key: O3DE-${{ matrix.platform }}-${{ matrix.config }}-ccache
          override_cache_key_fallback: |
            O3DE-${{ matrix.image }}-${{ matrix.config }}-ccache
          prepend_symlinks_to_path: false
          store_cache: false
          restore_cache: false
          ccache_options: |
            max_size=5G
            cache_dir=${{ github.workspace }}/.ccache
            
      - name: Restore ccache
        uses: actions/download-artifact@v4.1.8
        continue-on-error: true
        if: always()
        with:
          name: O3DE-${{ matrix.platform }}-ccache
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ vars.Linux_CCACHE_ARTIFACT_RUNID }}
          path: ${{ github.workspace }}/.ccache/

      - name: Restore build
        uses: actions/download-artifact@v4.1.8
        continue-on-error: true
        if: always()
        with:
          name: O3DE-${{ matrix.platform }}-build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: 11307473214

      - name: Extract build
        continue-on-error: true
        run: |
          tar --atime-preserve -xvpf ${{ github.workspace }}/cache.tar
          rm ${{ github.workspace }}/cache.tar

      - name: Configure environment
        continue-on-error: true
        if: always()
        run: |
          echo "Installing dependancies"
          pushd ./scripts/build/build_node/Platform/Linux
          sudo ./install-ubuntu.sh
          popd
          echo "Getting python..."
          ./python/get_python.sh
          
          echo "Installing desktop environment and tools"
          sudo apt-get update -qq -y
          sudo apt-get install -qq ubuntu-desktop xorg mesa-utils vulkan-tools libevdev-dev libevdev2 -y
          sudo apparmor_status
          sudo aa-teardown
          sudo apt-get --purge remove -qq apparmor
          sudo ufw disable
    
          sudo apt autoremove --purge
          sudo apt autoclean
          sudo apt clean
          
      - name: Build
        env:
          LY_3RDPARTY_PATH: ${{ github.workspace }}/3rdParty
          CC:  ${{ matrix.compiler == 'gcc' && 'gcc' || 'clang'   }}
          CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
          DISPLAY: :0
        run: |
          Xvfb :0 -screen 0 1400x1050x16 &
          output_file=$(mktemp)
          bypass_errors=(
            "AssetProcessor: JOB LOG: .* ERROR .* AssetBuilder .* failed to respond within 3600 seconds"
          )
          python/python.sh -u scripts/build/ci_build.py --platform "${{ matrix.platform }}" --type "${{ matrix.type }}" 2>&1 | tee "$output_file"
          exit_code=${PIPESTATUS[0]}
          bypass_exit_code=false
          while IFS= read -r line; do
            echo "$line"
            for error_pattern in "${bypass_errors[@]}"; do
              if [[ $line =~ $error_pattern ]]; then
                bypass_exit_code=true
                echo "::warning ::$line"
                break
              fi
            done
          done < "$output_file"
          if [ "$bypass_exit_code" = true ]; then
            exit 0
          else
            exit $exit_code
          fi
          rm "$output_file"

      - name: Compress build
        continue-on-error: true
        if: always()
        run: |
          tar --format=posix -cvpf ${{ github.workspace}}/cache.tar ${{ github.workspace }}/AutomatedTesting/Cache ${{ github.workspace }}/AutomatedTesting/user

      - name: Save build
        uses: actions/upload-artifact@v4.4.0
        continue-on-error: true
        if: always()
        with:
          name: O3DE-${{ matrix.platform }}-build
          compression-level: 1
          if-no-files-found: warn
          include-hidden-files: true
          path: |
            ${{ github.workspace }}/cache.tar
