name: Linux

on:
  push:
      paths: '.github/workflows/linux-profile.yml'
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang]
        config: [profile]
        image: [ubuntu-22.04]

    runs-on: ${{ matrix.image }}

    env:
      CC:  ${{ matrix.compiler == 'gcc' && 'gcc' || 'clang'   }}
      CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 7168
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-android: 'true'     
            
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
          repository: aws-lumberyard-dev/o3de
          ref: development
          
      - name: Cache 3p
        uses: actions/cache@v4.0.2
        continue-on-error: true
        with:
          path: |
            ${{ github.workspace }}/3rdParty/downloaded_packages
            ${{ github.workspace }}/python
          key: O3DE-${{ matrix.image }}-3p
          save-always: true

      - name: Use ccache
        uses: hendrikmuhs/ccache-action@v1.2.12
        with:
          key: O3DE-linux-${{ matrix.image }}-${{ matrix.config }}-${{ matrix.compiler }}
          max-size: 2048M
          variant: ccache
        
      - name: Configure environment
        run: |
          echo "Installing dependancies"
          pushd ./scripts/build/build_node/Platform/Linux
          sudo ./install-ubuntu.sh
          popd
          echo "Getting python..."
          ./python/get_python.sh
         
      - name: Configure
        run: |
          echo "Generating project..."
          cmake -B build -G "Ninja Multi-Config" -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -D CMAKE_C_COMPILER_LAUNCHER=ccache -DLY_3RDPARTY_PATH=./3rdParty
          
      - name: Build
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cmake --build build --target Editor --config ${{ matrix.config }} -j3
