name: Linux Profile

on:
  push:
      paths: '.github/workflows/linux-profile.yml'
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang]
        config: [profile]
        image: [ubuntu-22.04]

    runs-on: ${{ matrix.image }}

    steps:                  
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
        with:
          show-progress: false
          clean: false
          
      - name: Git LFS fetch
        run: |
          git lfs install
          git lfs fetch --include "*.ico,*.bmp"
          git lfs checkout
          
      - name: Restore 3P Cache
        uses: actions/cache/restore@v4.0.2
        continue-on-error: true
        with:
          path: |
            /dev/shm/3rdParty/packages
            ${{ github.workspace }}/python
          key: O3DE-${{ matrix.image }}-3p

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1.4.3
        with:
          override_cache_key: O3DE-${{ matrix.image }}-${{ matrix.config }}-ccache
          override_cache_key_fallback: |
            O3DE-${{ matrix.image }}-${{ matrix.config }}
          prepend_symlinks_to_path: false
          ccache_options: |
            max_size=5G
            cache_dir=/dev/shm/.ccache

      - name: Configure environment
        run: |
          echo "Installing dependancies"
          pushd ./scripts/build/build_node/Platform/Linux
          sudo ./install-ubuntu.sh
          popd
          echo "Getting python..."
          ./python/get_python.sh
          sudo apt -y autoremove --purge
          sudo apt -y autoclean
          sudo apt clean
          df -h
          
      - name: Build
        env:
          LY_3RDPARTY_PATH: /dev/shm/3rdParty
          CC:  ${{ matrix.compiler == 'gcc' && 'gcc' || 'clang'   }}
          CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          python/python.sh -u scripts/build/ci_build.py --platform Linux --type profile_unity

      - name: Get disk space
        run: |
          df -h
          ls -lah ${{ github.workspace }}

      - name: Save 3P Cache
        uses: actions/cache/save@v4.0.2
        continue-on-error: true
        if: always()
        with:
          path: |
            /dev/shm/3rdParty/packages
            ${{ github.workspace }}/python
          key: O3DE-${{ matrix.image }}-3p
