name: MacOS Profile

on:
  push:
      paths: '.github/workflows/mac-profile.yml'
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [xcode]
        config: [profile]
        image: [macos-13]
        platform: [Mac]

    runs-on: ${{ matrix.image }}

    steps:    
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Git LFS fetch
        run: |
          git lfs install
          git lfs fetch --include "*.ico,*.bmp"
          git lfs checkout

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2
          
      - name: Restore 3p cache
        uses: actions/cache/restore@v4.0.2
        continue-on-error: true
        with:
          path: |
            ${{ github.workspace }}/3rdParty/downloaded_packages
            ${{ github.workspace }}/python
            ~/work/o3de/o3de/python
          key: O3DE-${{ matrix.image }}-3p
          save-always: true
          
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1.4.3
        continue-on-error: true
        if: always()
        with:
          override_cache_key: O3DE-${{ matrix.image }}-ccache
          override_cache_key_fallback: |
            O3DE-${{ matrix.image }}-${{ matrix.config }}
          ccache_options: |
            max_size=5G

      - uses: lukka/get-cmake@latest
        
      - name: Configure environment
        run: |
          echo "Getting python..."
          ${{ github.workspace }}/python/get_python.sh
          
      - name: Build
        env:
          LY_3RDPARTY_PATH: ${{ github.workspace }}/3rdParty
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache
        run: |
          export PATH="/usr/local/bin/:/usr/local/opt/ccache/libexec:$PATH"
          ${{ github.workspace }}/python/python.sh -u scripts/build/ci_build.py --platform ${{ maxtrix.platform }} --type $ {{ matrix.config }}

      - name: Save 3p cache
        uses: actions/cache/save@v4.0.2
        continue-on-error: true
        with:
          path: |
            ${{ github.workspace }}/3rdParty/downloaded_packages
            ${{ github.workspace }}/python
            ~/work/o3de/o3de/python
          key: O3DE-${{ matrix.platform }}-3p
          save-always: true

      
