name: MacOS

on:
  push:
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [xcode]
        config: [profile]
        image: [macos-13]

    runs-on: ${{ matrix.image }}

    env:
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    steps:    
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
          ref: development
          
      - name: Cache 3p
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: |
            ./3rdParty/downloaded_packages
            ./python
          key: O3DE-mac-3p-${{ matrix.image }}

      - uses: hendrikmuhs/ccache-action@v1.2.12
        with:
          key: O3DE-mac-${{ matrix.image }}-${{ matrix.config }}-${{ matrix.compiler }}
          max-size: 2048M
          variant: ccache
        
      - name: Configure environment
        run: |
          brew install openssl
          echo "Getting python..."
          ./python/get_python.sh
         
      - name: Configure
        run: |
          echo "Generating project..."
          cmake -B build -DUSE_CCACHE=YES -DCCACHE_OPTIONS="CCACHE_CPP2=true;CCACHE_SLOPPINESS=clang_index_store" -DLY_3RDPARTY_PATH=./3rdParty
          
      - name: Build
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cmake --build build --target Editor --config ${{ matrix.config }} -j2
