name: Windows

on:
  push:
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc]
        config: [profile]
        target: [ALL_BUILD]
        image: [windows-2022]

    runs-on: ${{ matrix.image }}

    steps:               
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Git LFS fetch
        run: |
          git lfs install
          git lfs fetch --include "*.ico,*.bmp"
          git lfs checkout
      
      - name: Create binary folders
        run: |
          # "build","3rdParty" | % {New-Item "c:\o3de\$_" -ItemType 'Directory' -Force}
          "3rdParty" | % {New-Item "c:\o3de\$_" -ItemType 'Directory' -Force}
          "3rdParty" | % {New-Item -ItemType SymbolicLink -Name .\$_ -Target c:\o3de\$_ -Force}
                     
      - name: Restore 3P Cache
        uses: actions/cache/restore@v4
        continue-on-error: true
        with:
          path: |
            ${{ github.workspace }}\3rdParty\downloaded_packages
            ${{ github.workspace }}\python
            C:\Users\runneradmin\.o3de\Python
          key: O3DE-${{ matrix.image }}-3p
          restore-keys: |
            O3DE-windows-3p-
      
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1.4.3
        with:
          override_cache_key: O3DE-${{ matrix.image }}-${{ matrix.config }}-${{ matrix.target }}-ccache
          override_cache_key_fallback: |
            O3DE-${{ matrix.image }}-${{ matrix.config }}
          windows_compile_environment: msvc
          remove_stale_cache: false
          ccache_options: |
            max_size=10G
            cache_dir=${{ github.workspace }}\.ccache

      - uses: lukka/get-cmake@latest
        
      - name: Configure environment
        run: |
          echo "Installing dependancies"
          echo "Getting python..."
          python\get_python.bat
          
      - name: Add msbuild to PATH
        uses: ilammy/msvc-dev-cmd@v1.12.0
          
      - name: Build
        env:
          LY_3RDPARTY_PATH: ${{ github.workspace }}\3rdParty
        run: 
          python\python.cmd -u scripts\build\ci_build.py --platform Windows --type profile 

      - name: Save 3P Cache
        uses: actions/cache/save@v4
        continue-on-error: true
        if: always()
        with:
          path: |
            ${{ github.workspace }}\3rdParty\downloaded_packages
            ${{ github.workspace }}\python
            C:\Users\runneradmin\.o3de\Python
          key: O3DE-${{ matrix.image }}-3p
          
      - name: Compress Build
        continue-on-error: true
        if: always()
        run: 7z.exe a -t7z -mx=1 -mmt=3 -mtc -mta -mtm c:\o3de\build.7z ${{ github.workspace }}\build
      
      - name: Save build
        uses: actions/upload-artifact@v4
        continue-on-error: true
        if: always()
        with:
          path: c:\o3de\build.7z
          name: O3DE-${{ matrix.image }}-build-${{ matrix.config }}-${{ matrix.target }}
          compression-level: 0
