name: Windows

on:
  push:
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc]
        config: [profile]
        target: [ALL_BUILD]
        image: [windows-2022]

    runs-on: ${{ matrix.image }}

    steps:               
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Git LFS fetch
        run: |
          git lfs install
          git lfs fetch --include "*.ico,*.bmp"
          git lfs checkout

      - name: Restore DevDrive
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          path: "D:\\build.vhdx"
          name: O3DE-${{ matrix.image }}-build-${{ matrix.config }}-devdrive
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Mount DevDrive
        uses: samypr100/setup-dev-drive@v3
        with: 
          drive-path: "D:\\build.vhdx"
          mount-if-exists: true
      
      - name: Setup build and 3p folder
        run: |
          "build","3rdParty","python" | % {New-Item "e:\$_" -ItemType 'Directory' -Force}
          # "3rdParty" | % {New-Item "c:\o3de\$_" -ItemType 'Directory' -Force}
          "3rdParty" | % {New-Item -ItemType SymbolicLink -Name .\$_ -Target e:\$_ -Force}
          "build" | % {New-Item -ItemType SymbolicLink -Name .\$_ -Target e:\$_ -Force}
                     
      - name: Restore 3P Cache
        uses: actions/cache/restore@v4
        continue-on-error: true
        with:
          path: |
            ${{ github.workspace }}\python
            C:\Users\runneradmin\.o3de\Python
          key: O3DE-${{ matrix.image }}-python
          restore-keys: |
            O3DE-windows-3p-

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1.4.3
        with:
          override_cache_key: O3DE-${{ matrix.image }}-${{ matrix.config }}-${{ matrix.target }}-ccache
          override_cache_key_fallback: |
            O3DE-${{ matrix.image }}-${{ matrix.config }}
          windows_compile_environment: msvc
          remove_stale_cache: false
          ccache_options: |
            max_size=10G
            cache_dir=${{ env.DEV_DRIVE }}\.ccache

      - uses: lukka/get-cmake@latest
        
      - name: Configure environment
        run: |
          echo "Installing dependancies"
          echo "Getting python..."
          python\get_python.bat
          
      - name: Add msbuild to PATH
        uses: ilammy/msvc-dev-cmd@v1.12.0

      - name: Get environemnt
        run: |
          dir env:
          get-psdrive
          dir ${{ github.workspace }}
          dir ${{ github.workspace }}\build
          dir ${{ github.workspace }}\python
          dir ${{ github.workspace }}\3rdParty
          
      - name: Build
        env:
          LY_3RDPARTY_PATH: ${{ github.workspace }}\3rdParty
        run: 
          python\python.cmd -u scripts\build\ci_build.py --platform Windows --type profile 

      - name: Save Python Cache
        uses: actions/cache/save@v4
        continue-on-error: true
        if: always()
        with:
          path: |
            ${{ github.workspace }}\python
            C:\Users\runneradmin\.o3de\Python
          key: O3DE-${{ matrix.image }}-python
          
      - name: Save DevDrive
        uses: actions/upload-artifact@v4
        continue-on-error: true
        if: always()
        with:
          path: "D:\\build.vhdx"
          name: O3DE-${{ matrix.image }}-build-${{ matrix.config }}-devdrive
          compression-level: 1
