name: Windows

on:
  push:
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc]
        config: [profile]
        target: [editor]
        image: [windows-2022]

    runs-on: ${{ matrix.image }}

    steps:               
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      
      - name: Git LFS fetch
        run: |
          git lfs install
          git lfs fetch --include="*.ico"
          git lfs checkout
      
      - name: Create binary folders
        run: |
          "build","3rdParty" | % {New-Item "c:\o3de\$_" -ItemType 'Directory' -Force}
          "build","3rdParty" | % {New-Item -ItemType SymbolicLink -Name .\$_ -Target c:\o3de\$_ -Force}
                     
      - name: Cache 3p
        uses: actions/cache/restore@v4.0.2
        continue-on-error: true
        with:
          path: |
            ${{ github.workspace }}\3rdParty\downloaded_packages
            ${{ github.workspace }}\python
          key: O3DE-${{ matrix.image }}-3p
          restore-keys: |
            O3DE-windows-3p-
      
      - name: Cache build
        uses: actions/cache/restore@v4.0.2
        continue-on-error: true
        with:
          path: c:\o3de\build
          key: O3DE-${{ matrix.image }}-build-${{ matrix.config }}-${{ matrix.target }}
          restore-keys: |
            O3DE-windows-build-
            O3DE-${{ matrix.image }}-build-${{ matrix.config }}-${{ matrix.target }}

      - uses: lukka/get-cmake@latest
        
      - name: Configure environment
        run: |
          echo "Installing dependancies"
          echo "Getting python..."
          python\get_python.bat
          
      - name: Add msbuild to PATH
        uses: ilammy/msvc-dev-cmd@v1.12.0
      
      - name: Configure
        run: |
          echo "Generating project..."
          cmake -B c\o3de\build build -G "Visual Studio 17 2022" -DLY_3RDPARTY_PATH=3rdParty
          
      - name: Build
        run: 
          cmake --build c:\o3de\build --target ${{ matrix.target }} --config ${{ matrix.config }} -j3

      - name: Save cache 3p
        uses: actions/cache/save@v4.0.2
        continue-on-error: true
        if: always()
        with:
          path: |
            ${{ github.workspace }}\3rdParty\downloaded_packages
            ${{ github.workspace }}\python
          key: O3DE-${{ matrix.image }}-3p
      
      - name: Save cache build
        uses: actions/cache/save@v4.0.2
        continue-on-error: true
        if: always()
        with:
          path: c:\o3de\build
          key: O3DE-${{ matrix.image }}-build-${{ matrix.config }}-${{ matrix.target }}
