name: Windows

on:
  push:
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc]
        config: [profile]
        image: [windows-2022]

    runs-on: ${{ matrix.image }}

    env:
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    steps:               
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive
      
      - name: Create binary folders
        run: |
          "build","3rdParty" | % {New-Item -Name "c:\o3de\$_" -ItemType 'Directory' -Force}
          "build","3rdParty" | % {New-Item -ItemType SymbolicLink -Name .\$_ -Target c:\o3de\$_ -Force}
                     
      - name: Cache 3p
        uses: actions/cache@v3.0.11
        continue-on-error: true
        with:
          path: |
            3rdParty\downloaded_packages
            python
          key: O3DE-windows-3p-${{ matrix.image }}

      - uses: hendrikmuhs/ccache-action@v1.2.3
        with:
          key: O3DE-windows-${{ matrix.image }}-${{ matrix.config }}-${{ matrix.compiler }}
          max-size: 2048M
          variant: ccache
        
      - name: Configure environment
        run: |
          echo "Installing dependancies"
          echo "Getting python..."
          python\get_python.bat
         
      - name: Configure
        run: |
          echo "Generating project..."
          cmake -B build -G "Visual Studio 17 2022" -DLY_3RDPARTY_PATH=3rdParty
          
      - name: Build
        run: |
          cmake --build build --target Editor --config ${{ matrix.config }} -j1
