name: Windows

on:
  push:
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc]
        config: [profile]
        image: [windows-2022]

    runs-on: ${{ matrix.image }}

    env:
      CMAKE_C_COMPILER_LAUNCHER: sccache
      CMAKE_CXX_COMPILER_LAUNCHER: sccache

    steps:               
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Git LFS fetch
        run: |
          git lfs install
          git lfs fetch --include="*.ico"
          git lfs checkout
      
      - name: Create binary folders
        run: |
          "build","3rdParty" | % {New-Item "c:\o3de\$_" -ItemType 'Directory' -Force}
          "build","3rdParty" | % {New-Item -ItemType SymbolicLink -Name .\$_ -Target c:\o3de\$_ -Force}
                     
      - name: Cache 3p
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: |
            ${{ github.workspace }}\3rdParty\downloaded_packages
            ${{ github.workspace }}\python\
          key: O3DE-windows-3p-windows-2022
          save-always: true
      
      - name: Cache build
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: |
            ${{ github.workspace }}\build\
          key: O3DE-windows-build-windows-2022
          save-always: true
          
      - uses: hendrikmuhs/ccache-action@v1.2.12
        with:
          key: O3DE-windows-${{ matrix.image }}-${{ matrix.config }}-${{ matrix.compiler }}
          max-size: 2048M
          variant: sccache

      - uses: lukka/get-cmake@latest
        
      - name: Configure environment
        run: |
          echo "Installing dependancies"
          echo "Getting python..."
          python\get_python.bat
          
      - name: Add msbuild to PATH
        uses: ilammy/msvc-dev-cmd@v1.12.0
        
      - name: Configure
        run: |
          echo "Generating project..."
          cmake -B build -G "Ninja" -DLY_3RDPARTY_PATH=3rdParty -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          
      - name: Build
        run: 
          cmake --build build --target Editor --config ${{ matrix.config }} -j1
